name: redeploy the node app with the current code

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: fitness-coach

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH and restart PM2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd fitness-coach/

            pm2 stop index.js

            rm -rf node_modules/
            rm package-lock.json

            git pull

            npm install

            pm2 start index.js

            echo "PM2 restarted successfully"