name: redeploy the node app with the current code

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code (useful if you need repo files on the runner)
      - name: Checkout
        uses: actions/checkout@v3

      # 2. SSH into your Azure server and run the commands
      - name: SSH and restart PM2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}        # e.g., your Azure VM's IP or DNS
          username: ${{ secrets.SSH_USER }}    # e.g., azureuser
          key: ${{ secrets.SSH_KEY }}          # private key stored in GitHub Secrets
          script: |
            # Navigate to your app directory
            cd fitness-coach/

            # delete the node_modules folder 
            rm -rf node_modules/
            rm package-lock.json

            # (Optional) Pull latest changes if you're not using other deploy steps
            git pull origin main

            npm install

            # Restart the PM2 process
            pm2 stop index.js
            pm2 start index.js

            echo "PM2 restarted successfully"